"""
GST Validator Service — Session 2
------------------------------------
Cross-validates GSTR-2A/2B vs GSTR-3B.
Detects: ITC fraud, circular trading, revenue inflation.

Indian GST Context:
  - GSTR-2A: Auto-populated from supplier GSTR-1 (real-time, read-only)
  - GSTR-2B: Auto-drafted ITC statement (monthly, static)
  - GSTR-3B: Self-declared summary return (monthly)
  - Mismatch between 2A/2B (available ITC) and 3B (claimed ITC) = potential fraud
"""

import pandas as pd
from typing import Optional


# ─────────────────────────────────────────────
# GSTR-2B vs GSTR-3B COMPARISON
# ─────────────────────────────────────────────

def compare_gstr_2b_vs_3b(gstr_2b_data: dict, gstr_3b_data: dict) -> dict:
    """
    Compare ITC available (GSTR-2A/2B) vs ITC claimed (GSTR-3B) month by month.

    Indian GST Context:
    - GSTR-2A is auto-populated from supplier GSTR-1 filings (real-time view)
    - GSTR-2B is the static monthly ITC statement generated by GSTN
    - GSTR-3B is the self-declared summary return filed by the taxpayer
    - If claimed ITC (3B) > available ITC (2A/2B), it indicates overclaiming

    Input format:
        gstr_2b_data = {
            "2024-04": {"itc_available": 150000},
            "2024-05": {"itc_available": 200000},
            ...
        }
        gstr_3b_data = {
            "2024-04": {"itc_claimed": 145000, "turnover": 1200000},
            "2024-05": {"itc_claimed": 230000, "turnover": 1500000},  # ← FRAUD FLAG
            ...
        }

    Returns:
        {
            "monthly_analysis": [...],
            "flags": [...],
            "total_excess_claimed": float,
            "fraud_risk": "LOW" | "MEDIUM" | "HIGH"
        }
    """
    monthly_analysis = []
    flags = []
    total_excess = 0.0

    all_months = sorted(set(list(gstr_2b_data.keys()) + list(gstr_3b_data.keys())))

    for month in all_months:
        available = gstr_2b_data.get(month, {}).get("itc_available", 0)
        claimed   = gstr_3b_data.get(month, {}).get("itc_claimed", 0)
        turnover  = gstr_3b_data.get(month, {}).get("turnover", 0)

        delta = claimed - available  # Positive = over-claimed (BAD)
        delta_pct = (delta / available * 100) if available > 0 else 0

        flag = None
        if delta > 0 and delta_pct > 5:
            flag = {
                "month": month,
                "type": "ITC_OVERCLAIM",
                "severity": "HIGH" if delta_pct > 20 else "MEDIUM",
                "detail": f"Claimed ₹{claimed:,.0f} vs Available ₹{available:,.0f} — excess {delta_pct:.1f}%"
            }
            flags.append(flag)
            total_excess += delta

        monthly_analysis.append({
            "month": month,
            "itc_available": available,
            "itc_claimed": claimed,
            "delta": delta,
            "delta_pct": round(delta_pct, 2),
            "turnover": turnover,
            "flag": flag["type"] if flag else None
        })

    # Overall risk rating
    if total_excess == 0:
        fraud_risk = "LOW"
    elif len([f for f in flags if f["severity"] == "HIGH"]) >= 2:
        fraud_risk = "HIGH"
    else:
        fraud_risk = "MEDIUM"

    return {
        "monthly_analysis": monthly_analysis,
        "flags": flags,
        "total_excess_claimed": round(total_excess, 2),
        "fraud_risk": fraud_risk,
        "summary": _build_gst_summary(flags, total_excess, fraud_risk)
    }


def _build_gst_summary(flags: list, total_excess: float, fraud_risk: str) -> str:
    if not flags:
        return "No ITC discrepancies detected. GST filings appear consistent."
    return (
        f"ALERT: {len(flags)} month(s) with ITC overclaim detected. "
        f"Total excess claimed: ₹{total_excess:,.0f}. "
        f"Overall fraud risk: {fraud_risk}."
    )


# ─────────────────────────────────────────────
# REVENUE INFLATION CHECK
# ─────────────────────────────────────────────

def cross_check_revenue(
    gstr_turnover_monthly: dict,
    bank_credits_monthly: dict,
    threshold_pct: float = 20.0
) -> dict:
    """
    Compare GST-declared turnover vs actual bank credits received.
    Large gap = possible revenue inflation on paper.

    Input:
        gstr_turnover_monthly = {"2024-04": 1200000, "2024-05": 1500000, ...}
        bank_credits_monthly  = {"2024-04": 950000,  "2024-05": 1490000, ...}
        threshold_pct = flag if GST turnover > bank credits by this % or more
    """
    flags = []
    monthly = []

    all_months = sorted(set(list(gstr_turnover_monthly.keys()) + list(bank_credits_monthly.keys())))

    for month in all_months:
        gst_rev  = gstr_turnover_monthly.get(month, 0)
        bank_rev = bank_credits_monthly.get(month, 0)

        if gst_rev == 0:
            gap_pct = 0.0
        else:
            gap_pct = ((gst_rev - bank_rev) / gst_rev) * 100

        flag = None
        if gap_pct > threshold_pct:
            flag = {
                "month": month,
                "type": "REVENUE_INFLATION",
                "severity": "HIGH" if gap_pct > 40 else "MEDIUM",
                "detail": f"GST turnover ₹{gst_rev:,.0f} vs Bank credits ₹{bank_rev:,.0f} — gap {gap_pct:.1f}%"
            }
            flags.append(flag)

        monthly.append({
            "month": month,
            "gst_turnover": gst_rev,
            "bank_credits": bank_rev,
            "gap_pct": round(gap_pct, 2),
            "flag": flag["type"] if flag else None
        })

    return {
        "monthly_analysis": monthly,
        "flags": flags,
        "revenue_inflation_risk": "HIGH" if len(flags) >= 3 else ("MEDIUM" if flags else "LOW"),
        "summary": _build_revenue_summary(flags)
    }


def _build_revenue_summary(flags: list) -> str:
    if not flags:
        return "Revenue appears consistent between GST filings and bank statements."
    return (
        f"WARNING: Revenue inflation suspected in {len(flags)} month(s). "
        f"GST-declared turnover significantly exceeds actual bank credits. "
        f"Possible manipulation of revenue figures."
    )


# ─────────────────────────────────────────────
# CIRCULAR TRADING DETECTION
# ─────────────────────────────────────────────

def detect_circular_trading(transactions: list) -> dict:
    """
    Detect circular trading patterns.
    A circular trade = Company A sells to B, B sells to C, C sells back to A.
    This inflates revenue with no real economic activity.

    Input: list of transaction dicts:
        [
            {"from": "CompanyA", "to": "CompanyB", "amount": 500000, "month": "2024-04"},
            {"from": "CompanyB", "to": "CompanyC", "amount": 490000, "month": "2024-04"},
            {"from": "CompanyC", "to": "CompanyA", "amount": 480000, "month": "2024-04"},
        ]
    """
    if not transactions:
        return {
            "circular_trading_detected": False,
            "suspicious_chains": [],
            "risk": "LOW",
            "summary": "No transaction data provided for circular trading analysis."
        }

    # Build adjacency: who sells to whom
    df = pd.DataFrame(transactions)
    sell_map = {}  # seller -> list of buyers

    for _, row in df.iterrows():
        seller = row["from"]
        buyer  = row["to"]
        if seller not in sell_map:
            sell_map[seller] = []
        sell_map[seller].append(buyer)

    # Detect cycles: A → B → A or A → B → C → A
    suspicious_chains = []

    for start_entity in sell_map:
        visited = {start_entity}
        path = [start_entity]

        def dfs(current):
            for next_entity in sell_map.get(current, []):
                if next_entity == start_entity and len(path) > 1:
                    suspicious_chains.append(list(path) + [start_entity])
                elif next_entity not in visited and len(path) < 5:
                    visited.add(next_entity)
                    path.append(next_entity)
                    dfs(next_entity)
                    path.pop()
                    visited.remove(next_entity)

        dfs(start_entity)

    detected = len(suspicious_chains) > 0

    return {
        "circular_trading_detected": detected,
        "suspicious_chains": suspicious_chains,
        "risk": "HIGH" if detected else "LOW",
        "summary": (
            f"CRITICAL: {len(suspicious_chains)} circular trading chain(s) detected. "
            f"Immediate investigation required."
            if detected else
            "No circular trading patterns detected in provided transaction data."
        )
    }


# ─────────────────────────────────────────────
# BANK STATEMENT ANALYSIS
# ─────────────────────────────────────────────

def analyse_bank_statement(transactions: list) -> dict:
    """
    Analyse bank statement transactions for red flags.

    Input: list of bank transaction dicts:
        [
            {"date": "2024-04-05", "type": "credit", "amount": 500000, "narration": "NEFT from XYZ"},
            {"date": "2024-04-07", "type": "debit",  "amount": 200000, "narration": "EMI payment"},
            {"date": "2024-04-10", "type": "debit",  "amount": 50000,  "narration": "Cheque return charges"},
            ...
        ]
    """
    if not transactions:
        return {"error": "No transaction data provided"}

    df = pd.DataFrame(transactions)
    df["amount"] = pd.to_numeric(df["amount"], errors="coerce").fillna(0)

    # Total credits and debits
    credits = df[df["type"] == "credit"]["amount"].sum()
    debits  = df[df["type"] == "debit"]["amount"].sum()
    net_flow = credits - debits

    # Cheque return / bounce detection
    bounced_narrations = ["cheque return", "return charges", "bounce", "dishonour"]
    bounced = df[
        df["narration"].str.lower().str.contains("|".join(bounced_narrations), na=False)
    ]
    bounce_count = len(bounced)

    # Large round-number transactions (possible layering)
    round_number_threshold = 100000
    round_txns = df[
        (df["amount"] % round_number_threshold == 0) &
        (df["amount"] >= round_number_threshold)
    ]

    # Build flags
    flags = []
    if bounce_count >= 3:
        flags.append({
            "type": "CHEQUE_BOUNCES",
            "severity": "HIGH",
            "detail": f"{bounce_count} cheque return(s) found — liquidity stress signal"
        })
    if len(round_txns) > (len(df) * 0.3):
        flags.append({
            "type": "ROUND_NUMBER_TRANSACTIONS",
            "severity": "MEDIUM",
            "detail": f"{len(round_txns)} large round-number transactions — possible fund layering"
        })

    return {
        "total_credits": round(credits, 2),
        "total_debits": round(debits, 2),
        "net_flow": round(net_flow, 2),
        "bounce_count": bounce_count,
        "total_transactions": len(df),
        "flags": flags,
        "summary": _build_bank_summary(credits, debits, bounce_count, flags)
    }


def _build_bank_summary(credits, debits, bounces, flags) -> str:
    parts = [
        f"Total Credits: ₹{credits:,.0f}",
        f"Total Debits: ₹{debits:,.0f}",
        f"Cheque Bounces: {bounces}"
    ]
    if flags:
        parts.append(f"Flags: {', '.join([f['type'] for f in flags])}")
    return " | ".join(parts)
